### ISSUE TITLE
Android搭載のマイナンバーカードの利用者証明書でruntime error

### ISSUE THREAD

**Issue by luminjp** [jpki/myna#6]
Android搭載のマイナンバーカードの利用者証明書(myna jpki cert auth )でエラー (runtime error: )が出ます。署名用の電子証明書は正常に動いているようです。同じ環境でマイナンバーカードでは正常に動いています。

```cmd
myna-0.4.2-windows-x64>myna jpki cert auth
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0xb8 pc=0x6038cc]

goroutine 1 [running]:
github.com/jpki/myna/libmyna.(*JPKICertificate).ToString(0xc04206bc70, 0x6936a2, 0x4)
        /home/user/work/src/github.com/jpki/myna/libmyna/jpki_ap.go:172 +0x5c
github.com/jpki/myna/cmd.outputCert(0x0, 0x7dbb40, 0x0, 0x4)
        /home/user/work/src/github.com/jpki/myna/cmd/jpki.go:86 +0x177
github.com/jpki/myna/cmd.jpkiCert(0x7dbb40, 0xc04203a830, 0x1, 0x1, 0x0, 0x0)
        /home/user/work/src/github.com/jpki/myna/cmd/jpki.go:74 +0x142
github.com/spf13/cobra.(*Command).execute(0x7dbb40, 0xc04203a800, 0x1, 0x1, 0x7dbb40, 0xc04203a800)
        /home/user/work/src/github.com/spf13/cobra/command.go:762 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0x7db1c0, 0xc0420080b8, 0x0, 0xc04203a590)
        /home/user/work/src/github.com/spf13/cobra/command.go:852 +0x33b
github.com/spf13/cobra.(*Command).Execute(0x7db1c0, 0x0, 0x0)
        /home/user/work/src/github.com/spf13/cobra/command.go:800 +0x32
github.com/jpki/myna/cmd.Execute()
        /home/user/work/src/github.com/jpki/myna/cmd/root.go:35 +0x34
main.main()
        /builds/hamano/myna/main.go:6 +0x27
```

**Comment by hamano** [comment]
お、card emurationに対応したんですね。
証明書の読み出しにPIN認証が必要となっていたので、暫定的に
```
$ myna jpki cert mauth
```

を用意しました。
カードJPKIとモバイルJPKIの区別はできそうなので最終的に、

```
$ myna jpki cert auth
```

で両方対応できるようにします。

**Comment by luminjp** [comment]
```
> myna jpki cert mauth
```
で正常動作を確認しました。他のアプリケーションも対応していないので、各所で情報共有しておきます。ありがとうございました。
